name: Debug Build

on:
  push:
    branches: ["main"]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Debug files
        run: |
          echo "=== Estructura de archivos ==="
          find . -name "*.md" -o -name "*.yml" | grep -v "_site" | sort
          echo "=== Config.yml ==="
          cat _config.yml
          echo "=== Gemfile ==="
          cat Gemfile

      - name: Build with verbose output
        run: |
          bundle exec jekyll build --verbose --trace